<?php
    declare(strict_types=1);
    /** @var YouTubeVideoTaggerExtension $this */
?>
<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <div class="form-group">
        <label class="group-name" for="short_duration"><?= _t('ext.YouTubeVideoTagger.shorts.duration.label'); ?></label>
        <div class="group-controls">
            <input type="number" name="short_duration" id="short_duration" value="<?= $this->getShortDuration(); ?>">
            <br /><span><?= _t('ext.YouTubeVideoTagger.shorts.duration.hint') ?></span>
        </div>
    </div>

    <div class="form-group">
        <label class="group-name" for="youtube_api_token"><?= _t('ext.YouTubeVideoTagger.youtube_api_token.label'); ?></label>
        <div class="group-controls">
            <input type="string" name="youtube_api_token" id="youtube_api_token" value="<?= $this->getYoutubeAPIToken(); ?>">
            <br /><span><?= _t('ext.YouTubeVideoTagger.youtube_api_token.hint') ?></span>
        </div>
    </div>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
            <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
        </div>
    </div>
</form>
